<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GET project-category</name>
   <tag></tag>
   <elementGuidId>5c141329-69db-41db-bb3e-3adc9e7ab5f7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ebb164a5-f1cf-41c7-8b1b-005921bf0623</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NmJlMmZjLTc5ZDQtNGVmMC05YTEyLTJkZmZjOGQ0OWFhOSIsIm5hbWUiOiJBbXBvcm5zYWsiLCJmYW1pbHlOYW1lIjoiQW5na2F0YXZhbmljaCIsImVtYWlsIjoiYW1wb3Juc2FrLmFAY3JlYXRpdmVtZS5jby50aCIsInJvbGUiOnsiaWQiOiI2NzMwZTY5Ny0xMGIzLTQxODItYjI0ZC05MmE1MjczOGNiZDEiLCJuYW1lIjoiQ1BOIEJJTSIsInBlcm1pc3Npb25LZXlzIjpbImFsYXJtLnBlcm1pc3Npb24uZGVsZXRlIiwiYWdlbnQuaGlzdG9yeS52aWV3IiwiY2N0di5ncm91cC5kZWxldGUiLCJwcm9qZWN0LnN0YXR1cy5kZWxldGUiLCJwaG9uZV9ib29rLmRldGFpbC5kZWxldGUiLCJyZXBhaXIuaGlzdG9yeS51cGRhdGUiLCJwcm9qZWN0LnN0YXR1cy52aWV3IiwicXVlc3Rpb25uYWlyZS5kZXRhaWwudmlldyIsImNhdGVnb3J5LmRldGFpbC5kZWxldGUiLCJhZ2VudC5kZXRhaWwudmlldyIsInJlcGFpci5oaXN0b3J5LmNyZWF0ZSIsImFsYXJtLmdyb3VwLmRlbGV0ZSIsImNhdGVnb3J5LmNyZWF0ZSIsImNhdGVnb3J5LmRldGFpbC52aWV3Iiwic2V0dGluZy5kZXRhaWwuZGVsZXRlIiwiYWRzLmRldGFpbC51cGRhdGUiLCJwcm9qZWN0LnVuaXQuY3JlYXRlIiwiYXBwX3VzYWdlLnJlcXVlc3QuY3JlYXRlIiwiY2F0ZWdvcnkuZGVsZXRlIiwiYWdlbnQuZGV0YWlsLnVwZGF0ZSIsInZtcy5ncm91cC52aWV3IiwiYXBwX3JlcG9ydC5oaXN0b3J5LnVwZGF0ZSIsImFkbWluLmRldGFpbC52aWV3IiwiYWdlbnQuaGlzdG9yeS5kZWxldGUiLCJzZXJ2aWNlLmRldGFpbC51cGRhdGUiLCJwcm9qZWN0LnVuaXQudXBkYXRlIiwiYWxhcm0ucGVybWlzc2lvbi52aWV3IiwiYWxhcm0ucGVybWlzc2lvbi51cGRhdGUiLCJhbGFybS5ncm91cC5jcmVhdGUiLCJjY3R2LnBlcm1pc3Npb24udXBkYXRlIiwiYXBwX3VzYWdlLmhpc3RvcnkudXBkYXRlIiwiYXBwX3JlcG9ydC5oaXN0b3J5LnZpZXciLCJjY3R2LmRldGFpbC52aWV3IiwiYXBwX3JlcG9ydC5oaXN0b3J5LmRlbGV0ZSIsImNjdHYucGVybWlzc2lvbi52aWV3IiwiYWxhcm0uZ3JvdXAudmlldyIsImNjdHYucGVybWlzc2lvbi5jcmVhdGUiLCJwcm9qZWN0LnVuaXQuZGVsZXRlIiwiY2N0di5ncm91cC5jcmVhdGUiLCJzdXBlcl9hZG1pbi5kZXRhaWwudmlldyIsInZtcy5wZXJtaXNzaW9uLmRlbGV0ZSIsImFkcy5kZXRhaWwuZGVsZXRlIiwicXVlc3Rpb25uYWlyZS5kZXRhaWwuY3JlYXRlIiwicHJvamVjdC5jYXRlZ29yeS52aWV3IiwicHJvamVjdC5jYXRlZ29yeS5jcmVhdGUiLCJwcm9qZWN0LmNhdGVnb3J5LnVwZGF0ZSIsInByb2plY3QuY2F0ZWdvcnkuZGVsZXRlIiwiY2F0ZWdvcnkudmlldyIsImFwcF91c2FnZS5yZXF1ZXN0LnZpZXciLCJyZXBhaXIuaGlzdG9yeS5kZWxldGUiLCJwcm9qZWN0LmRldGFpbC5jcmVhdGUiLCJjYXRlZ29yeS51cGRhdGUiLCJjY3R2LmRldGFpbC5jcmVhdGUiLCJwcm9qZWN0LmRldGFpbC51cGRhdGUiLCJhZHMuZGV0YWlsLnZpZXciLCJhcHBfcmVwb3J0LnJlcXVlc3QuY3JlYXRlIiwiYXBwX3JlcG9ydC5yZXF1ZXN0LnVwZGF0ZSIsInZtcy5ncm91cC5jcmVhdGUiLCJ2bXMucGVybWlzc2lvbi51cGRhdGUiLCJjYXRlZ29yeS5kZXRhaWwuY3JlYXRlIiwiY2N0di5ncm91cC52aWV3IiwiYWRzLmRldGFpbC5jcmVhdGUiLCJyZXBhaXIucmVxdWVzdC51cGRhdGUiLCJ2bXMuZ3JvdXAudXBkYXRlIiwicmVwYWlyLmhpc3RvcnkudmlldyIsImFwcF91c2FnZS5yZXF1ZXN0LnVwZGF0ZSIsImFwcF91c2FnZS5yZXF1ZXN0LmRlbGV0ZSIsInByb2plY3QudW5pdC52aWV3IiwicmVwYWlyLnJlcXVlc3QuZGVsZXRlIiwicHJvamVjdC5kZXRhaWwuZGVsZXRlIiwic2V0dGluZy5kZXRhaWwuY3JlYXRlIiwicHJvamVjdC5kZXRhaWwudmlldyIsImFwcF9yZXBvcnQucmVxdWVzdC52aWV3IiwiY2N0di5kZXRhaWwudXBkYXRlIiwidm1zLmdyb3VwLmRlbGV0ZSIsImFsYXJtLnBlcm1pc3Npb24uY3JlYXRlIiwicXVlc3Rpb25uYWlyZS5kZXRhaWwuZGVsZXRlIiwicGhvbmVfYm9vay5kZXRhaWwuY3JlYXRlIiwiY2F0ZWdvcnkuZGV0YWlsLnVwZGF0ZSIsInJlcGFpci5yZXF1ZXN0LmNyZWF0ZSIsInJlcGFpci5yZXF1ZXN0LnZpZXciLCJhbGFybS5ncm91cC51cGRhdGUiLCJhZG1pbi5kZXRhaWwudXBkYXRlIiwic2V0dGluZy5kZXRhaWwudmlldyIsInByb2plY3Quc3RhdHVzLnVwZGF0ZSIsInBob25lX2Jvb2suZGV0YWlsLnZpZXciLCJhcHBfcmVwb3J0LnJlcXVlc3QuZGVsZXRlIiwicHJvamVjdC5tZW1iZXIudmlldyIsInZtcy5wZXJtaXNzaW9uLmNyZWF0ZSIsImFnZW50Lmhpc3RvcnkudXBkYXRlIiwidm1zLnBlcm1pc3Npb24udmlldyIsInByb2plY3Quc3RhdHVzLmNyZWF0ZSIsInByb2plY3QubWVtYmVyLmNyZWF0ZSIsImFnZW50LmRldGFpbC5kZWxldGUiLCJhZ2VudC5oaXN0b3J5LmNyZWF0ZSIsImFwcF91c2FnZS5oaXN0b3J5LmNyZWF0ZSIsInNldHRpbmcuZGV0YWlsLnVwZGF0ZSIsInNlcnZpY2UuZGV0YWlsLmNyZWF0ZSIsImFkbWluLmRldGFpbC5kZWxldGUiLCJhZ2VudC5kZXRhaWwuY3JlYXRlIiwic2VydmljZS5kZXRhaWwuZGVsZXRlIiwiY2N0di5wZXJtaXNzaW9uLmRlbGV0ZSIsInByb2plY3QubWVtYmVyLnVwZGF0ZSIsImFwcF91c2FnZS5oaXN0b3J5LmRlbGV0ZSIsInF1ZXN0aW9ubmFpcmUuZGV0YWlsLnVwZGF0ZSIsImFkbWluLmRldGFpbC5jcmVhdGUiLCJjY3R2LmRldGFpbC5kZWxldGUiLCJzZXJ2aWNlLmRldGFpbC52aWV3IiwicGhvbmVfYm9vay5kZXRhaWwudXBkYXRlIiwiY2N0di5ncm91cC51cGRhdGUiLCJhcHBfcmVwb3J0Lmhpc3RvcnkuY3JlYXRlIl19LCJpYXQiOjE3MTU2NzMzMzMsIm5iZiI6MTcxNTY3MzMzMywiZXhwIjoxNzE1NzU5NzMzLCJpc3MiOiJodHRwczovL3Jlc2lkZW50aWFsZmFtaWx5LmNlbnRyYWxwYXR0YW5hLmNvLnRoIn0._yt9qFx_nK-CjQl03DLaOmKN825UrUmJ21z2iZgoG9g</value>
      <webElementGuid>7ad77cd9-af53-4273-973c-aae9930f84fd</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://45.150.131.146:7090/api-backoffice/project/service/category?page=1&amp;limit=10</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>a8d19e03-7ba7-47f0-9293-e2f5f65fd861</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
